application: chu-food
version: 1-2016-05-01
runtime: python27
api_version: 1
threadsafe: true

skip_files: |
 ^(.*/)?(
 (.*/\.svn/.*)|
 (.*/Thumbs\.db)|
 )$

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/x-icon

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /css
  static_dir: css

- url: /fonts
  static_dir: fonts

- url: /images
  static_dir: images

- url: /static
  static_dir: static

- url: /js
  static_dir: js

- url: /player
  static_dir: player

# css files
- url: /(.*\.css)
  mime_type: text/css
  static_files: \1
  upload: (.*\.css)

# htc files
- url: /(.*\.htc)
  mime_type: text/x-component
  static_files: \1
  upload: (.*\.htc)

# html files
- url: /(.*\.html)
  mime_type: text/html
  static_files: \1
  upload: (.*\.html)

# htm files
- url: /(.*\.htm)
  mime_type: text/html
  static_files: \1
  upload: (.*\.htm)

# ico files
- url: /(.*\.ico)
  mime_type: image/x-icon
  static_files: \1
  upload: (.*\.ico)

# js files
- url: /(.*\.js)
  mime_type: text/javascript
  static_files: \1
  upload: (.*\.js)

# rss files
- url: /(.*\.rss)
  mime_type: application/rss+xml
  static_files: \1
  upload: (.*\.rss)

# swf files
- url: /(.*\.swf)
  mime_type: application/x-shockwave-flash
  static_files: \1
  upload: (.*\.swf)

# txt files
- url: /(.*\.txt)
  mime_type: text/plain
  static_files: \1
  upload: (.*\.txt)

# xml files
- url: /(.*\.xml)
  mime_type: application/xml
  static_files: \1
  upload: (.*\.xml)

# image files
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: \1
  upload: (.*\.(bmp|gif|ico|jpeg|jpg|png))

# audio files
- url: /(.*\.(mid|midi|mp3|wav))
  static_files: \1
  upload: (.*\.(mid|midi|mp3|wav)) 

# windows files
- url: /(.*\.(doc|ppt|rtf|xls))
  static_files: \1
  upload: (.*\.(doc|ppt|rtf|xls))

# compressed files
- url: /(.*\.(bz2|gz|rar|tar|tgz|zip))
  static_files: \1
  upload: (.*\.(bz2|gz|rar|tar|tgz|zip))

# index files
- url: /(.+)/
  static_files: \1/index.html
  upload: (.+)/index.html

- url: /(.*)/
  static_files: \1/index.html
  upload: (.*)/index.html

# site root
- url: /
  static_files: index.html
  upload: index.html
